### ISSUE TITLE
missing x-axis of "yearly proportion of words in topic" plot

### ISSUE THREAD

**Issue by style-x7** [agoldst/dfr-browser#1]
Hi there,

1st, thank you so much for the project :+1: 

In the master version, when I run it, under topic view, the x-axis of "yearly proportion of words in topic" plot seems to be "covered" and went missing.

I'm using Chrome/Ubuntu.

![browser_issue](https://cloud.githubusercontent.com/assets/8356229/14408834/19016f94-ff37-11e5-9408-cb2c846c29e2.png)

**Comment by agoldst** [comment]
Thanks! Hmm. I can't reproduce this on Chrome/Mac and don't have an Ubuntu system handy. I think you mean "y-axis" rather than x-axis (the x-axis is visible, though for some reason it has only one tick, which is also odd). As a quick fix you could try manually adjusting the margin left for the axis labels by setting `VIS.topic_view.m.left` to something bigger than its [default value of 40](https://github.com/agoldst/dfr-browser/blob/master/src/VIS.js#L59). You can do this by adding the corresponding property in your `info.json`.

Do you see the same x-axis problem in Chrome/Ubuntu when you visit the [demo](http://agoldst.github.io/dfr-browser/demo/#/topic/8)? --And in a window of the same dimensions.

**Comment by style-x7** [comment]
Hi agoldst, yep it's the y-axis (Oops!)

Tried VIS.topic_view.m.left and it works. The x-axis has only one tick because my dfr data set is limited 10 years. I'm getting more ticks by tweaking the "ticks" value in VIS.

The demo works fine too :)

Thanks!

**Comment by agoldst** [comment]
You're very welcome--glad that helped!
