### ISSUE TITLE
"use strict" in utils.js

### ISSUE THREAD

**Issue by pleonard212** [agoldst/dfr-browser#2]
In recent versions of WebKit (Safari 9.1, Chrome 50.0.2661.86) declaring `use strict` in utils.min.js seems to lead to the following error

`TypeError: Attempted to assign to readonly property.`

I believe the line in the minified version:

`f[r] = t(n[r], e[r])`

corresponds with line 58 of the non-minified version:

`result[prop] = deep_replace(x[prop], repl[prop]);`

It's entirely possible this is a WebKit bug; in the meantime, removing 

`"use strict";`

from utils.min.js seems to make the problem go away.

**Comment by agoldst** [comment]
Thanks, Peter, for the report and for looking into it closely. I don't seem to be able to replicate this error in Chrome 50.0.2661.94 on Yosemite or any other browser I have on hand, but the line looks like a plausible source of errors, since it is iterating over object properties and tries to replace any non-functions. But I can't think what the readonly property would be in this case. `utils.deep_replace` should only called be in two places: once to change the global `VIS` parameters using whatever's in the `data/info.json` file [here](https://github.com/agoldst/dfr-browser/blob/master/src/dfb.js#L749), and once to update the bibliography-formatting parameters using the `bib` property of the updated `VIS` [here](https://github.com/agoldst/dfr-browser/blob/master/src/dfb.js#L752). Did you do any modifications to the parameters? If you're willing to share them and the data files you're using, maybe I could diagnose better. E-mail if so! Otherwise of course feel free to make everything relaxed rather than `strict`.

The whole way the thing uses globals is messy in any case. Plus `deep_replace` looks suspiciously like I wrote it in the belief that JS objects are passed by value whereas in fact they are passed by reference. Not good. All this stuff desperately needs some refactoring, but I can't get to that for a little while.

**Comment by pleonard212** [comment]
Yeah, I somewhat suspect that an encoding gremlin in my bibliography is causing it (or, triggering an edge case that only affects WebKit.) I attach the metadata file only in case you are curious... it is from 100 years of _Scandinavian Studies_ so, umlauts abound.

[meta.csv.zip](https://github.com/agoldst/dfr-browser/files/243674/meta.csv.zip)

**Comment by agoldst** [comment]
Thanks for sharing that file. Anything is possible in the wild world of javascript, but I doubt that's the issue. I don't see your error when I use your metadata file (hard to fully check since I don't have a model of 4936 documents on hand so I get other errors related to the mismatch between number of doc-topic rows and number of metadata rows). In my far from comprehensive testing, dfr-browser appears to be unicode-friendly provided the input files are indeed utf8-encoded (as yours is). As I say, the first file I would check would be your `data/info.json`, if you have made any modifications there.

**Comment by pleonard212** [comment]
Agree that #3 fixes this.
