### ISSUE TITLE
Only displaying in Firefox

### ISSUE THREAD

**Issue by nealcaren** [agoldst/dfr-browser#3]
My first attempt works fine in Firefox, but seems not to load the data/models in Safari (Version 9.1 (11601.5.17.1)) or Chrome (Version 51.0.2704.19 dev (64-bit)). This happens when I Open the file in the browser, set up a local server, or try a [server](http://sociologicalresearch.org/sf/index.html) on the internet.

**Comment by agoldst** [comment]
Thanks for the report and especially for the link to the example! This looks to be the same TypeError @pleonard212 was talking about in #2 but which I couldn't replicate in his case. Now I'll take a closer look using your example. This seems likely to be a regression due to ba1dfd3999de4ad19ad1fbc2e07284a49373abc5 which changed the way data stuffed into the HTML source was loaded. In the meanwhile, for a workaround, if you are making the model using my dfrtopics package you could try re-exporting with `dfr_browser(m, "sf", internalize=F)`.

**Comment by nealcaren** [comment]
Thanks. I gave `dfr_browser(m, "sf", internalize=FALSE)` a try and updated the [site](http://sociologicalresearch.org/sf/) but it didn't seem to change anything.

**Comment by agoldst** [comment]
Okay, I think the issue is with the `dfrtopics::dfr_browser()` export of the `data/info.json` file. Try reinstalling dfrtopics (which I just patched, agoldst/dfrtopics@4d8203ada6fb022f9ceb17b015d91a11b2ce1a92) and re-exporting (either `internalize=F` or `=T` should work, and set `overwrite=T`). If you have `internalize=F` then in <http://sociologicalresearch.org/sf/data/info.json> you should see a change from

````
{"title":["Model Browser"],"meta_info":["<h2></h2>"],"VIS":{"overview_words":[15]}}
````

to

````
{"title":"Model Browser","meta_info":"<h2></h2>","VIS":{"overview_words":15}}
````

And in any case please let me know if that still doesn't fix the issue!

**Comment by pleonard212** [comment]
This fix worked for me! (Haven't tried updating and re-exporting, but did test the info.json fix and can confirm that's what was going on)...

**Comment by nealcaren** [comment]
The fix works for me too. Thanks so much.

**Comment by agoldst** [comment]
Great! glad that worked. Would love to know more about how either of you is using my thing--and if it does in fact prove useful. My e-mail: andrew dot goldstone at rutgers dot edu. Best, Andrew
